const pets = [
  // 火系
  { id: 1, name: "火花", type: "火系", rarity: "普通", emoji: "🔥",
    stats: { hp: 45, atk: 60, def: 50, mag: 70, mdef: 55, spd: 65 },
    skills: ["火焰冲击", "火花溅射", "烈焰喷射"],
    evolution: "火花 → 焰火 → 火神",
    obtain: "初始宠物选择 / 宠物训练室",
    description: "充满活力的小火苗，总是蹦蹦跳跳，喜欢用火焰表达热情" },
  
  { id: 2, name: "焰火", type: "火系", rarity: "稀有", emoji: "🔥",
    stats: { hp: 60, atk: 75, def: 65, mag: 85, mdef: 70, spd: 80 },
    skills: ["烈焰风暴", "火焰漩涡", "燃烧冲击"],
    evolution: "火花 → 焰火 → 火神",
    obtain: "火花进化",
    description: "火焰更加旺盛，性格变得更加稳重，是值得信赖的伙伴" },
  
  { id: 3, name: "火神", type: "火系", rarity: "史诗", emoji: "🔥",
    stats: { hp: 85, atk: 95, def: 85, mag: 110, mdef: 90, spd: 100 },
    skills: ["神炎天降", "焚天烈焰", "火焰护盾", "炎神之怒"],
    evolution: "火花 → 焫火 → 火神",
    obtain: "焰火进化",
    description: "传说中的火系神宠，掌控着神圣的火焰力量，是火系的巅峰存在" },
  
  { id: 4, name: "烈火战神", type: "火系", rarity: "传说", emoji: "🔥",
    stats: { hp: 100, atk: 120, def: 95, mag: 115, mdef: 90, spd: 110 },
    skills: ["战神烈焰", "焚天灭世", "火焰领域", "战神之魂"],
    evolution: "火神 → 烈火战神",
    obtain: "火神进化 + 特殊道具",
    description: "火焰战神，拥有毁灭一切的火焰力量，是最强的火系宠物之一" },
  
  // 水系
  { id: 5, name: "水蓝蓝", type: "水系", rarity: "普通", emoji: "💧",
    stats: { hp: 55, atk: 45, def: 65, mag: 60, mdef: 70, spd: 55 },
    skills: ["水花溅射", "水泡攻击", "清凉水波"],
    evolution: "水蓝蓝 → 波波拉 → 水灵",
    obtain: "初始宠物选择 / 宠物训练室",
    description: "清澈的小水珠，性格温柔善良，喜欢帮助他人" },
  
  { id: 6, name: "波波拉", type: "水系", rarity: "稀有", emoji: "💧",
    stats: { hp: 70, atk: 60, def: 80, mag: 75, mdef: 85, spd: 70 },
    skills: ["水波漩涡", "水幕屏障", "清流冲击"],
    evolution: "水蓝蓝 → 波波拉 → 水灵",
    obtain: "水蓝蓝进化",
    description: "水流更加充沛，学会了保护伙伴的水幕技能" },
  
  { id: 7, name: "水灵", type: "水系", rarity: "史诗", emoji: "💧",
    stats: { hp: 95, atk: 80, def: 100, mag: 95, mdef: 110, spd: 85 },
    skills: ["灵水天降", "水神庇护", "清泉治愈", "水灵之息"],
    evolution: "水蓝蓝 → 波波拉 → 水灵",
    obtain: "波波拉进化",
    description: "水系的神宠，拥有纯净的水灵之力，能够治愈和保护伙伴" },
  
  { id: 8, name: "圣水守护", type: "水系", rarity: "传说", emoji: "💧",
    stats: { hp: 120, atk: 95, def: 110, mag: 100, mdef: 125, spd: 90 },
    skills: ["圣水审判", "水神祝福", "净化之泉", "守护屏障"],
    evolution: "水灵 → 圣水守护",
    obtain: "水灵进化 + 特殊道具",
    description: "最神圣的水系守护者，能够净化一切邪恶力量" },
  
  // 草系
  { id: 9, name: "草草", type: "草系", rarity: "普通", emoji: "🌿",
    stats: { hp: 50, atk: 55, def: 55, mag: 65, mdef: 60, spd: 50 },
    skills: ["草叶飞舞", "种子投掷", "藤蔓缠绕"],
    evolution: "草草 → 蒲公英 → 草神",
    obtain: "初始宠物选择 / 宠物训练室",
    description: "可爱的小草苗，喜欢阳光和雨露，性格活泼可爱" },
  
  { id: 10, name: "蒲公英", type: "草系", rarity: "稀有", emoji: "🌿",
    stats: { hp: 65, atk: 70, def: 70, mag: 80, mdef: 75, spd: 65 },
    skills: ["蒲公英飞舞", "治愈花粉", "自然之力"],
    evolution: "草草 → 蒲公英 → 草神",
    obtain: "草草进化",
    description: "轻盈的蒲公英，随风飘扬，能够散播治愈的花粉" },
  
  { id: 11, name: "草神", type: "草系", rarity: "史诗", emoji: "🌿",
    stats: { hp: 90, atk: 90, def: 90, mag: 105, mdef: 100, spd: 80 },
    skills: ["草木之心", "自然祝福", "生命绽放", "草神之力"],
    evolution: "草草 → 蒲公英 → 草神",
    obtain: "蒲公英进化",
    description: "草系的神宠，掌控着大自然的生命力量" },
  
  // 电系
  { id: 12, name: "电咩咩", type: "电系", rarity: "普通", emoji: "⚡",
    stats: { hp: 40, atk: 65, def: 45, mag: 75, mdef: 50, spd: 85 },
    skills: ["电光闪烁", "电流冲击", "雷电跳跃"],
    evolution: "电咩咩 → 电灵",
    obtain: "宠物训练室 / 电系地图",
    description: "毛茸茸的小羊，身上带着电光，性格温顺但速度极快" },
  
  { id: 13, name: "电灵", type: "电系", rarity: "史诗", emoji: "⚡",
    stats: { hp: 75, atk: 95, def: 70, mag: 105, mdef: 80, spd: 115 },
    skills: ["雷电风暴", "电光护盾", "闪电突击", "电灵之力"],
    evolution: "电咩咩 → 电灵",
    obtain: "电咩咩进化",
    description: "电系的神宠，掌控雷电之力，速度是所有宠物中最快的" },
  
  // 冰系
  { id: 14, name: "雪精灵", type: "冰系", rarity: "稀有", emoji: "❄️",
    stats: { hp: 60, atk: 55, def: 75, mag: 80, mdef: 85, spd: 60 },
    skills: ["冰雪飞舞", "冰霜护盾", "冰冻之息"],
    evolution: "雪精灵 → 冰灵",
    obtain: "冰系地图 / 冬日活动",
    description: "纯净的雪精灵，能够在寒冬中自由飞舞" },
  
  { id: 15, name: "冰灵", type: "冰系", rarity: "史诗", emoji: "❄️",
    stats: { hp: 90, atk: 85, def: 95, mag: 110, mdef: 105, spd: 80 },
    skills: ["冰霜风暴", "冰神庇护", "冰封天地", "冰灵之怒"],
    evolution: "雪精灵 → 冰灵",
    obtain: "雪精灵进化",
    description: "冰系神宠，掌控绝对的冰雪之力，能够冰封一切" },
  
  // 龙系
  { id: 16, name: "小翼龙", type: "龙系", rarity: "稀有", emoji: "🐉",
    stats: { hp: 65, atk: 80, def: 60, mag: 85, mdef: 65, spd: 90 },
    skills: ["龙翼飞翔", "龙息喷吐", "龙之爪"],
    evolution: "小翼龙 → 翼龙 → 龙神",
    obtain: "龙系地图 / 特殊活动",
    description: "可爱的小龙，虽然翅膀还小但飞行能力很强" },
  
  { id: 17, name: "翼龙", type: "龙系", rarity: "史诗", emoji: "🐉",
    stats: { hp: 85, atk: 100, def: 80, mag: 105, mdef: 85, spd: 110 },
    skills: ["龙神之翼", "龙息烈焰", "龙之领域", "翼龙风暴"],
    evolution: "小翼龙 → 翼龙 → 龙神",
    obtain: "小翼龙进化",
    description: "强大的翼龙，龙系的中级形态，拥有强大的飞行和战斗能力" },
  
  { id: 18, name: "龙神", type: "龙系", rarity: "传说", emoji: "🐉",
    stats: { hp: 110, atk: 130, def: 100, mag: 120, mdef: 95, spd: 125 },
    skills: ["龙神天降", "龙之怒吼", "神龙摆尾", "龙神领域"],
    evolution: "小翼龙 → 翼龙 → 龙神",
    obtain: "翼龙进化 + 特殊道具",
    description: "传说中的龙系神宠，是所有龙系的巅峰存在，拥有毁灭一切的力量" },
  
  // 幽灵系
  { id: 19, name: "幽灵娃娃", type: "幽灵系", rarity: "稀有", emoji: "👻",
    stats: { hp: 50, atk: 70, def: 45, mag: 90, mdef: 60, spd: 75 },
    skills: ["幽灵缠绕", "暗影袭击", "鬼魅消失"],
    evolution: "幽灵娃娃 → 幽灵王",
    obtain: "幽灵地图 / 万圣节活动",
    description: "神秘的幽灵娃娃，喜欢在夜晚出没，性格神秘莫测" },
  
  { id: 20, name: "幽灵王", type: "幽灵系", rarity: "传说", emoji: "👻",
    stats: { hp: 85, atk: 110, def: 75, mag: 125, mdef: 95, spd: 100 },
    skills: ["幽灵领域", "暗影吞噬", "亡灵召唤", "幽灵王之怒"],
    evolution: "幽灵娃娃 → 幽灵王",
    obtain: "幽灵娃娃进化 + 特殊道具",
    description: "幽灵系的王者，掌控着暗影和亡灵的力量" },
  
  // 普通系
  { id: 21, name: "小洛克", type: "普通系", rarity: "普通", emoji: "🦁",
    stats: { hp: 50, atk: 50, def: 50, mag: 50, mdef: 50, spd: 50 },
    skills: ["洛克之拳", "普通攻击", "鼓舞"],
    evolution: "小洛克 → 洛克勇士",
    obtain: "初始伙伴",
    description: "洛克的初始伙伴，陪伴你开始冒险之旅" },
  
  // 更多热门宠物
  { id: 22, name: "迪莫", type: "光系", rarity: "传说", emoji: "✨",
    stats: { hp: 95, atk: 115, def: 90, mag: 120, mdef: 100, spd: 105 },
    skills: ["光辉圣剑", "光明庇护", "圣光治愈", "光神降临"],
    evolution: "迪莫（初始形态）",
    obtain: "特殊活动 / 限时获取",
    description: "光系的神宠，拥有最纯净的光明力量，是洛克王国的守护者之一" },
  
  { id: 23, name: "洛克狮", type: "火系", rarity: "史诗", emoji: "🦁",
    stats: { hp: 90, atk: 105, def: 85, mag: 100, mdef: 90, spd: 95 },
    skills: ["狮王烈焰", "王者咆哮", "火焰领域", "狮王之怒"],
    evolution: "小洛克狮 → 洛克狮",
    obtain: "火系地图 / 活动获取",
    description: "火焰狮子，拥有王者的气质和强大的火焰力量" },
  
  { id: 24, name: "冰龙王", type: "冰系", rarity: "传说", emoji: "❄️",
    stats: { hp: 115, atk: 120, def: 105, mag: 130, mdef: 110, spd: 95 },
    skills: ["冰龙之息", "冰霜领域", "冰封万物", "冰龙咆哮"],
    evolution: "冰龙 → 冰龙王",
    obtain: "冰系活动 / 限时活动",
    description: "冰系和龙系的完美结合，拥有冰龙双属性的最强宠物" },
  
  { id: 25, name: "暗夜魔王", type: "幽灵系", rarity: "传说", emoji: "🌙",
    stats: { hp: 100, atk: 125, def: 80, mag: 135, mdef: 90, spd: 110 },
    skills: ["暗夜降临", "魔王之怒", "黑暗吞噬", "噩梦领域"],
    evolution: "暗夜精灵 → 暗夜魔王",
    obtain: "万圣节活动 / 幽灵地图",
    description: "暗夜的王者，在黑夜中拥有绝对的力量" },
  
  { id: 26, name: "圣光迪莫", type: "光系", rarity: "神话", emoji: "✨",
    stats: { hp: 120, atk: 135, def: 110, mag: 145, mdef: 115, spd: 120 },
    skills: ["圣光审判", "光神降临", "光辉领域", "神圣庇护"],
    evolution: "迪莫 → 圣光迪莫",
    obtain: "迪莫进化 + 特殊道具",
    description: "光系最强的存在，拥有神圣的光明审判之力" },
  
  { id: 27, name: "火舞烈焰", type: "火系", rarity: "史诗", emoji: "🔥",
    stats: { hp: 85, atk: 110, def: 80, mag: 105, mdef: 85, spd: 115 },
    skills: ["火焰舞步", "烈焰华尔兹", "火舞风暴", "舞者之魂"],
    evolution: "火舞精灵 → 火舞烈焰",
    obtain: "火系活动",
    description: "优雅的火焰舞者，将火焰与舞蹈完美结合" },
  
  { id: 28, name: "水晶龙", type: "水系", rarity: "传说", emoji: "💎",
    stats: { hp: 105, atk: 100, def: 115, mag: 125, mdef: 120, spd: 85 },
    skills: ["水晶护盾", "水龙之息", "晶化领域", "水晶治愈"],
    evolution: "水晶精灵 → 水晶龙",
    obtain: "水系活动 / 限时获取",
    description: "水系和龙系的结合，拥有水晶般的纯净力量" },
  
  { id: 29, name: "精灵王", type: "草系", rarity: "传说", emoji: "🧚",
    stats: { hp: 100, atk: 110, def: 95, mag: 130, mdef: 105, spd: 90 },
    skills: ["精灵祝福", "自然领域", "生命绽放", "精灵王之怒"],
    evolution: "精灵 → 精灵王",
    obtain: "草系活动 / 自然地图",
    description: "森林的精灵王者，守护着大自然的平衡" },
  
  { id: 30, name: "雷霆战神", type: "电系", rarity: "传说", emoji: "⚡",
    stats: { hp: 95, atk: 125, def: 85, mag: 115, mdef: 90, spd: 130 },
    skills: ["雷霆审判", "闪电领域", "战神咆哮", "雷神之怒"],
    evolution: "电灵 → 雷霆战神",
    obtain: "电灵进化 + 特殊道具",
    description: "电系的最强战神，掌控雷霆审判之力" }
];